### ISSUE TITLE
Remove HTML font codes

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/tools#109]
The tN writers are all using the WYSIWYG editor and pasting in a large amount of HTML font code.  Please create a script to automatically find and delete this code at least once per day.  

This script should only check the en:bible:notes and en:obe namespaces. Some pages, such as https://door43.org/en/bible/home contain legitimate code. It is possible we may want to add other namespaces at a later date.

These pages show the current list of pages:  https://door43.org/en/bible/resources/code/find-font-code-notes and https://door43.org/en/bible/resources/code/find-font-code-obe.

**Comment by lrsallee** [comment]
Seems straight-forward, but let me know if you have any questions. larry_sallee@wycliffeassociates.org

**Comment by superdav42** [comment]
@jag3773 @lrsallee I think it would make a lot more sense to fix update the editor to strip out the font codes or update docuwiki to strip them out on save. Automatically running a global search and replace seems like a bad idea.

**Comment by lrsallee** [comment]
David,

However you solve the problem is fine with us. We only care about the end result—not code throughout the text.

Larry

From: superdav42
Reply-To: unfoldingWord-dev/tools
Date: Thursday, July 23, 2015 at 7:38 PM
To: unfoldingWord-dev/tools
Cc: Larry Sallee
Subject: Re: [tools] Remove HTML font codes (#109)


@jag3773<https://github.com/jag3773> @lrsallee<https://github.com/lrsallee> I think it would make a lot more sense to fix update the editor to strip out the font codes or update docuwiki to strip them out on save. Automatically running a global search and replace seems like a bad idea.

**Comment by alerque** [comment]
I would concur with what @superdav42 said here. One additional benefit to doing this at the editor level (as a save hook or filter of some sort) has the major advantage of catching problems as they happen rather than later. If you do this later you might mess something up that the author saved and checked and thought was done and they moved on. Who knows when you would even catch that something unexpected happened. But if you do it as part of the save process, the editor that entered content in the first place will be checking the actual final result of their work and immediately be aware if there is a problem.

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord-dev/Door43#243
