### ISSUE TITLE
Updated etherpad export to pull from Github

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/tools#163]
After #161, we need to update the script that exports from etherpad to the catalog, https://github.com/unfoldingWord-dev/tools/blob/master/uwb/ep_export.py .

**Comment by richmahn** [comment]
Since this no longer comes from EP, but from the Github repos locally on the server, this script is now:

https://github.com/unfoldingWord-dev/tools/blob/master/uwb/make_book_from_chapters.py

It outputs to the Door43 or API directories based on the -v tag (draft, etc.). Works the same way as ep_export.py in regards to arguments and output.
